### ISSUE TITLE
请教一下关于文件缺失的问题

### ISSUE THREAD

**Issue by zxjlm** [FuYanzhe2/Name-Entity-Recognition#11]
运行 __fyz_lattice_NER__ 时报错如下：

> FileNotFoundError: [Errno 2] No such file or directory: 'test_data/fyz.train.embs'

请问是不是缺失了这部分的文件？

纯萌新，因为最近的研究需要参考您的这部分代码，望不吝赐教。:D

**Comment by lidongdong328** [comment]
同问？到底是什么问题

**Comment by lidongdong328** [comment]
> 运行 **fyz_lattice_NER** 时报错如下：
> 
> > FileNotFoundError: [Errno 2] No such file or directory: 'test_data/fyz.train.embs'
> 
> 请问是不是缺失了这部分的文件？
> 
> 纯萌新，因为最近的研究需要参考您的这部分代码，望不吝赐教。:D

同问？解决了吗？
